<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers AS Crs;


Route::resource('category', Crs\CategoryController::class);
Route::resource('language', Crs\LanguageController::class);
Route::resource('meditator', Crs\MeditatorController::class);
Route::post('meditator-upload/{meditator}', [Crs\MeditatorController::class, 'upload'])->name('meditator-upload');
Route::post('meditator-reupload/{meditator}/{asset}', [Crs\MeditatorController::class, 'reupload'])->name('meditator-reupload');
Route::delete('meditator-unupload/{meditator}/{asset}', [Crs\MeditatorController::class, 'unupload'])->name('meditator-unupload');
Route::get('meditator-avatar/{meditator}', [Crs\MeditatorController::class, 'avatar'])->name('meditator-avatar-view');
Route::get('meditator-image/{meditator}', [Crs\MeditatorController::class, 'image'])->name('meditator-image-view');
Route::resource('meditation', Crs\MeditationController::class);
Route::resource('lesson', Crs\LessonController::class);
Route::get('lesson-audio-upload/{lesson}', [Crs\LessonController::class, 'audioCreate'])->name('lesson-audio-upload-view');
Route::post('lesson-audio-upload/{lesson}', [Crs\LessonController::class, 'audioStore'])->name('lesson-audio-upload');
Route::post('lesson-audio-update/{lesson}/{audio}', [Crs\LessonController::class, 'audioUpdate'])->name('lesson-audio-update');
Route::get('lesson-audio-update/{lesson}/{audio}', [Crs\LessonController::class, 'audioEdit'])->name('lesson-audio-update-view');
Route::get('lesson-audio-download/{lesson}/{audio}', [Crs\LessonController::class, 'audioDownload'])->name('lesson-audio-download');
Route::delete('lesson-audio-delete/{lesson}/{audio}', [Crs\LessonController::class, 'audioDelete'])->name('lesson-audio-delete');
Route::get('lesson-image/{lesson}', [Crs\LessonController::class, 'image'])->name('lesson-image-view');
Route::post('lesson-image-upload/{lesson}', [Crs\LessonController::class, 'upload'])->name('lesson-image-upload');
Route::post('lesson-image-reupload/{lesson}/{asset}', [Crs\LessonController::class, 'reupload'])->name('lesson-image-reupload');
Route::resource('motivation', Crs\MotivationController::class);
Route::resource('gratitude', Crs\GratitudeController::class);
Route::resource('issue', Crs\IssueController::class);
Route::post('issue-upload/{issue}', [Crs\IssueController::class, 'upload'])->name('issue-upload');
Route::post('issue-reupload/{issue}/{asset}', [Crs\IssueController::class, 'reupload'])->name('issue-reupload');
Route::delete('issue-unupload/{issue}/{asset}', [Crs\IssueController::class, 'unupload'])->name('issue-unupload');
Route::get('issue-image/{issue}', [Crs\IssueController::class, 'image'])->name('issue-image-view');
Route::resource('question', Crs\QuestionController::class);
Route::resource('variant', Crs\VariantController::class);
Route::resource('emoji', Crs\EmojiController::class);
Route::post('emoji-upload/{emoji}', [Crs\EmojiController::class, 'upload'])->name('emoji-upload');
Route::post('emoji-reupload/{emoji}/{asset}', [Crs\EmojiController::class, 'reupload'])->name('emoji-reupload');
Route::delete('emoji-unupload/{emoji}/{asset}', [Crs\EmojiController::class, 'unupload'])->name('emoji-unupload');
Route::get('emoji-image/{emoji}', [Crs\EmojiController::class, 'image'])->name('emoji-image-view');
Route::resource('landscape', Crs\LandscapeController::class);
Route::post('landscape-upload/{landscape}', [Crs\LandscapeController::class, 'upload'])->name('landscape-upload');
Route::post('landscape-reupload/{landscape}/{asset}', [Crs\LandscapeController::class, 'reupload'])->name('landscape-reupload');
Route::delete('landscape-unupload/{landscape}/{asset}', [Crs\LandscapeController::class, 'unupload'])->name('landscape-unupload');
Route::get('landscape-image/{landscape}', [Crs\LandscapeController::class, 'image'])->name('landscape-image-view');
Route::get('landscape-video/{landscape}', [Crs\LandscapeController::class, 'video'])->name('landscape-video-view');
Route::get('landscape-audio/{landscape}', [Crs\LandscapeController::class, 'audio'])->name('landscape-audio-view');
Route::resource('medicine', Crs\MedicineController::class);
Route::resource('package', Crs\PackageController::class);
Route::get('package-image/{package}', [Crs\PackageController::class, 'image'])->name('package-image-view');
Route::post('package-image-upload/{package}', [Crs\PackageController::class, 'upload'])->name('package-image-upload');
Route::post('package-image-reupload/{package}/{asset}', [Crs\PackageController::class, 'reupload'])->name('package-image-reupload');
Route::delete('package-image-unupload/{package}/{asset}', [Crs\PackageController::class, 'unupload'])->name('package-image-unupload');
Route::resource('test', Crs\TestController::class);
Route::resource('answer', Crs\AnswerController::class);
Route::resource('steroid', Crs\SteroidController::class);
Route::resource('steroidinfo', Crs\SteroidinfoController::class);
Route::resource('rule', Crs\RuleController::class);